### ISSUE TITLE
the avatar avatar path is not with port setting

### ISSUE THREAD

**Issue by chan15** [umputun/remark#391]
remark docker env

```
REMARK_URL=http://10.10.10.16:8080                                                                                                                                                             
REMARK_PORT=8080    
```

html include js 

```
 var remark_config = {
   host: "http://10.10.10.16:8080",
   site_id: 'remark',
 };
```

the widget was loaded successfully, but the avatar path did not load with port

> http://10.10.10.16/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image

**Comment by umputun** [comment]
I can't reproduce it. In fact, provided compose-dev-*.yml listen on :8080 as well and stores avatars just fine (with correct url). 

Did you run remark42 with the same site prior to this with `REMARK_URL=http://10.10.10.16` and posted some comments? If this is the case the avatar's URL will be stored at the moment you posted a comment and avatar will have no port in. There is no automatic migration of urls if port was changed.

**Comment by chan15** [comment]
the avatar stores correct, the file was built, and most APIs run correctly

![image](https://user-images.githubusercontent.com/1229833/61922890-94530480-af94-11e9-99b1-176dee06295e.png)

for example, remark.js required from `http://10.10.10.16:8080/web/remark.js`, but avatar goes wrong, it requires to `http://10.10.10.16/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image`, lack of port

**Comment by umputun** [comment]
> the avatar stores correct

avatar's URL is not calculated in runtime but used as a static resource in the way as it was stored. If you see a request to `http://10.10.10.16/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image` it means there is a post (or posts) created by a user with such avatar's url and rendered html has a link to this image.

You can try to hit `/last` of `/find` API endpoints and should see the url `http://10.10.10.16/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image` as `user.avatar`.

Have you tried to post another comment? Do you see a lack of avatar in all comments or just one of them?

**Comment by chan15** [comment]
I mean, the avatar exits in http://10.10.10.16:8080/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image, but frontend load it without port

**Comment by umputun** [comment]
I get it, but my point was - this url saved in each comment. This is why I asked all those questions. As I said - the only way I think it may happen if you run remark42 once without `REMARK_URL` param or with `REMARK_URL=http://10.10.10.16` and posted a comment. This was the reason why I asked to provide more information, like "Have you tried to post another comment? Do you see a lack of avatar in all comments or just one of them?". 

_Without answers, I can't say what is wrong and how to fix it because I see no issue in the code and can't reproduce your results._

**Comment by chan15** [comment]
**docker-copmpose.yml**

```
version: '2'

services:
    remark42:
        image: umputun/remark42:master
        restart: always
        container_name: "remark42"
        ports:
            - 8080:8080
        environment:
            - ADMIN_PASSWD=1234
            - REMARK_URL=http://10.10.10.16
            - SITE=remark
            - SECRET=abcd-123456-xyz-$$%^&
            - AUTH_ANON=true
        volumes:
            - ./var:/srv/var
```

**javascript setting**

```
  var remark_config = {
    host: "http://10.10.10.16:8080",
    site_id: 'remark',
        theme: 'light'
  };
```
I cleared all var directory and rebuild the docker container, the comment list is clean, and I login as anonymous, post works fine, but the avatar requires failed, it still requires to `http://10.10.10.16/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image`, but the correct URL is `http://10.10.10.16:8-8-/api/v1/avatar/8c5002ab5a2d1f5d7a0c12e3b9fceb5693a08387.image`, other script work with remark_config.host, only avatar don't
